vich_uploader:
    db_driver: orm
    mappings:
        coach_images:
            uri_prefix: 'images/coach'
            upload_destination: '%kernel.project_dir%/public/uploades/images/coaches'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            delete_on_remove: true
            delete_on_update: true